Task 2: SSP
kznts9v-1lya/high-performance-graph-analysis-course pull request #2
Opened 2022-04-14 18:38 UTC by kznts9v-1lya

# Задача 2. Реализация поиска кратчайших путей

* **Мягкий дедлайн**: ---
* **Жёсткий дедлайн**: 14.04.2022, 23:59
* Полный балл: 15

## Задача

Везде считаем, что вершины графа занумерованы подряд с нуля.
Обратите внимание на то, что про граф заранее не известно, есть ли в нём циклы отрицательного веса.

- [x] Используя pygraphblas реализовать функцию поиска кратчайших путей в ориентированном графе из заданной вершины.
  - [x] Функция принимает представление графа, удобное для неё (загрузка, конвертация реализованы отдельно) и номер стартовой вершины.
  - [x] Функция возвращает массив, где для каждой вершины указано расстояние до неё от указанной стартовой вершины. Если вершина не достижима, то значение соответствующей ячейки равно -1.
- [x] Используя pygraphblas реализовать функцию поиска кратчайших путей в ориентированном графе из нескольких заданных вершин.
  - [x] Функция принимает представление графа, удобное для неё (загрузка, конвертация реализованы отдельно) и массив номеров стартовых вершин.
  - [x] Функция возвращает массив пар: вершина, и массив, где для каждой вершины указано расстояние до неё из указанной. Если вершина не достижима, то значение соответствующей ячейки равно -1.
- [x] Добавить необходимые тесты.

2022-05-28 17:30 UTC, gsvgit requested changes

2022-05-28 17:30 UTC, gsvgit commented on project/bfs.py
> +from typing import List, Set, Tuple
Да зачем же ж всё в одну кучу мешать.

2022-05-29 22:36 UTC, kznts9v-1lya commented on project/bfs.py
> +from typing import List, Set, Tuple
Действительно можно обойтись без Set. В task 3 также будет поправлено.

А вообще старался поддержать тот же интерфейс, что и в прошлом семестре.

2022-05-30 07:56 UTC, gsvgit commented
А ещё у Вас тут конфликты подъехали. Угимся пользоваться Гитом)

2022-05-30 10:44 UTC, kznts9v-1lya commented
Делать такую структуру веток было плохой идеей. Исправил здесь, в task 3 также будет поправлено.

2022-06-04 18:17 UTC, gsvgit commented on project/ssp.py
> +    for _ in range(adj_matrix.nrows):
А можно ли как-то экономить на количестве итераций? Хотя бы иногда.

2022-06-06 14:24 UTC, closed without merging

2022-06-06 15:01 UTC, i1ya-kznts9v commented on project/ssp.py
> +    for _ in range(adj_matrix.nrows):
Оптимизировал в новом PR