Task 4: DC
kznts9v-1lya/high-performance-graph-analysis-course pull request #4
Opened 2022-05-17 20:15 UTC by kznts9v-1lya

# Задача 4. Динамическая связность.

* **Мягкий дедлайн**: 28.04.2022, 23:59
* **Жёсткий дедлайн**: 19.05.2022, 23:59
* Полный балл: 15

## Задача

- [x] Придумайте рекурсивную процедуру fall(v), которая для вершины v, такой, что N 1 (v) = ∅, “роняет” v на правильный уровень BFS-дерева, корректно обновляет уровни соседей v и “роняет” те вершины, чей уровень изменился при падении v. 
- [x] Докажите, что если в графе n вершин и m рёбер изначально, на все обновления суммарно при удалении m рёбер уйдет время O(mn).
- [x] Пусть вместо всего BFS-дерева нам разрешено хранить только BFS-дерево с d уровнями, т.е. структура будет поддерживать только расстояния до вершин v, такие, что d(s, v) ≤ d. Докажите, что суммарное время на все обновления в этом случае равно O(md).

2022-05-17 20:55 UTC, katyacyfra requested changes
1. Как нужно поменять код, чтобы не использовать N_3_old?
2. _В случае, когда BFS-дерево вырождается в список,_ ... Что значит "вырождается в список"? В каких случаях такая ситуация будет наблюдаться?
3. _Тогда наибольшее число вызовов рекурсивной процедуры f all, начатых из вершины v, тоже можно сравнить с n._ --- Можно поподробнее: как именно число рекурсивных вызовов процедуры зависит от высоты дерева?

2022-05-18 19:37 UTC, kznts9v-1lya commented
1. Оптимизировал в псевдокоде (см. pdf)
2. В вырожденном случае может оказаться, что все левое дерево пусто на каждом уровне и есть только правые деревья (или ситуация наоборот), то в таком случае дерево выродиться в список. Если говорить не про граф, а в целом, то такое может быть, если исходная последовательность упорядочена по возрастанию или убыванию ключей, то мы получим в итоге список. Если говорить про нашу задачу, то BFS-дерево почти вырождается в список в случае графа, как на фото.
<img width="191" alt="image" src="https://user-images.githubusercontent.com/55543776/169141889-cb29dfe7-6c2d-41b7-be92-c36c998284c4.png">
3.

2022-05-19 20:34 UTC, katyacyfra approved these changes
Хорошо. Правда ответ на пункт 2 недостаточно общий, дерево может быть более "ветвистым", но всё равно иметь высоту порядка n, например, на каждом уровне у вершины константное число детей, и только у одного из этих детей есть дети. Ну не суть, пример Вы правильный привели. 5 баллов (-5 за использование готового решения другого студента)

2022-05-26 16:34 UTC, kznts9v-1lya commented
Добавил второе задание в тот же pdf.

2022-05-30 14:18 UTC, katyacyfra requested changes
1. Теперь рассмотрим цикл C = (C1 ∪ C2) (C1 ∩ C2) --- что это за цикл? Выражение математически некорректное, какой-то знак пропущен между скобками?Запахло бездумным копипастом... Почему мы рассматриваем именно такой цикл?
2. Раз Вы ссылаетесь на статью, расскажите кратко основную идею доработки алгоритма до поддержки полностью динамической рёберной двусвязности (секция 6). Только своими словами, а не копипастом теорем с переводом на русский.

2022-05-30 15:45 UTC, kznts9v-1lya commented
1. Объединение позволяет сформировать цикл, в котором содержатся ребра e1 и e2. Это нужно, чтобы показать, что так как ребро е2 имеет самый большой вес, а значит по инварианту самый низкий уровень в этом цикле, а значит, что его уровень меньше, чем у е1. Удаление пересечения циклов C1 и C2 из объединения нужно, чтобы убрать из рассмотрения ребро е, которое удалилось из графа и самого остовного дерева. Вот на примере ниже минимальное остовное дерево. Представим, что ребро e удалилось, объединение циклов C1 (1-2-8-7-3-1) с C2 (7-8-10-11-7) добавит ребра e1 и е2 в рассмотрение, а разность удалит ребро е.
<img width="374" alt="image" src="https://user-images.githubusercontent.com/55543776/171025604-13293220-0a1a-4a25-b434-842f949cb4b0.png">

2. Секция 3 рассматривает задачу декремент динамической связности, но в ином виде, секция 4 же описывает, как сделать алгоритм минимального остовного дерева, но при этом имея другой порядок обхода уровней. Основная причина этого в том, что в статье уровни увеличиваются начиная с 0, а в нашей задаче понижаются начиная с log. От этого многие утверждения в статье меняются, как и инвариант. Если говорить про секцию 5, то честно скажу, я ее не читал, так она не требуется для выполнения поставленной задачи и не совсем относится к ней.

2022-05-30 18:11 UTC, katyacyfra approved these changes
Ок. Можно построить два варианта алгоритма с понижением уровней, как в лекции/ либо с повышением, как в статье. Оба варианта корректны, но условие задачи я не особо хорошо сформулировала, это да. Поэтому 10 баллов.

2022-06-25 16:23 UTC, merged